# Generated by Django 5.1.7 on 2025-03-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_heroimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroImage',
        ),
    ]
