# Generated by Django 5.1.7 on 2025-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_heroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sermons/')),
            ],
        ),
        migrations.DeleteModel(
            name='Sermon',
        ),
    ]
