# Generated by Django 5.1.7 on 2025-03-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sermons_delete_sermon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sermons',
            new_name='Sermon',
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
