# Generated by Django 5.1.7 on 2025-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_sermons_sermon_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sermon',
            options={},
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of the month when this event repeats (e.g., 15 for the 15th of every month).', null=True),
        ),
    ]
