# Generated by Django 5.1.7 on 2025-03-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sermon_options_event_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurring_week_position',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('last', 'Last')], help_text="Select which occurrence of the weekday (e.g., 'Last' for last Friday).", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_weekday',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Choose if this event happens on a specific weekday (e.g., last Friday of the month).', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurring_day',
            field=models.PositiveIntegerField(blank=True, help_text="Day of the month when this event repeats (e.g., 15 for the 15th of every month). Leave blank for 'last Friday' type events.", null=True),
        ),
    ]
