# Generated by Django 5.1.7 on 2025-03-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_recurring_week_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='recurring_day',
            field=models.PositiveIntegerField(blank=True, help_text='Day of the month when this event repeats (e.g., 15 for the 15th).', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurring_weekday',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Choose if this event happens on a specific weekday (e.g., last Friday).', null=True),
        ),
    ]
