# Generated by Django 5.1.7 on 2025-03-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
