# Generated by Django 5.1.7 on 2025-03-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
