# Generated by Django 5.1.7 on 2025-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_branch_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='membership_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
